services:
  app:
    build: .
    container_name: raceboxOverlay
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-exclude *tmp
    restart: no
    ports:
      - 8000:80
    volumes:
      - .:/app
#    secrets:
#      - TRONITY_USER
#      - TRONITY_PASS
